version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: ./deploy/app.Dockerfile
    restart: always
    volumes:
      - ./media_volume:/project/server/media/
      - ./static_volume:/project/server/static/
    env_file:
      - ./src/.env
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - bridge_bus

  next:
    build:
      context: .
      dockerfile: ./deploy/front.Dockerfile
    container_name: plenka-front
    restart: unless-stopped
    volumes:
      - images:/app/public
    networks:
      - bridge_bus

  nginx:
    build:
      context: .
      dockerfile: ./deploy/nginx.Dockerfile
    restart: always
    volumes:
      - ./media_volume:/project/server/media/
      - ./static_volume:/project/server/static/
    env_file:
      - ./src/.env
    expose:
      - "80"

  proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./media_volume:/project/server/media/
      - ./static_volume:/project/server/static/

  db:
    image: postgres:14-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
      - ./postgres_backups:/backups
    env_file:
      - ./src/.env
    expose:
      - "5432"