# Generated by Django 5.1.6 on 2025-03-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('contact_data', models.CharField(max_length=120, verbose_name='Контактные данные')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('contact_preference', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('email', 'Email')], max_length=30, verbose_name='Способ связи')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
            ],
        ),
    ]
