# Generated by Django 5.1.6 on 2025-03-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'Заявка обратной связи', 'verbose_name_plural': 'Заявки обратной связи'},
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обработана'),
        ),
    ]
