# Generated by Django 5.1.6 on 2025-03-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='news/previews/%Y/%m/%d')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('notification_status', models.CharField(choices=[('not_send', 'Не уведомлять'), ('to_send', 'Уведомлять'), ('is_send', 'Уведомления отправлены')], default='not_send', max_length=255)),
                ('tags', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/images/%Y/%m/%d')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'verbose_name': 'Изображение для новости',
                'verbose_name_plural': 'Изображения для новости',
            },
        ),
    ]
