# Generated by Django 5.1.6 on 2025-03-19 02:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_news_tags_alter_news_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='Текст новости'),
        ),
    ]
