# Generated by Django 5.1.6 on 2025-03-06 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlatPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('privacy_policy', 'Политика конфиденциальности'), ('site_rules', 'Правила пользования сайтом'), ('public_offer', 'Публичная оферта'), ('cookie_policy', 'Правила использования cookie'), ('user_agreement', 'Пользовательское соглашение'), ('legal_information', 'Юридическая информация'), ('refund_policy', 'Политика возврата средств'), ('partner_information', 'Стать партнером')], max_length=255, unique=True, verbose_name='Обозначение')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование')),
                ('text', models.TextField(null=True, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Плоская страница',
                'verbose_name_plural': 'Плоские страницы',
            },
        ),
    ]
