# Generated by Django 5.1.6 on 2025-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='title',
            field=models.CharField(choices=[('privacy_policy', 'Политика конфиденциальности'), ('cookie_policy', 'Правила использования cookie'), ('user_agreement', 'Пользовательское соглашение')], max_length=255, unique=True, verbose_name='Обозначение'),
        ),
    ]
