# Generated by Django 5.1.6 on 2025-03-19 02:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0002_alter_flatpage_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpage',
            name='text',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Текст'),
        ),
    ]
