# Generated by Django 5.1.6 on 2025-03-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_order_is_done_order_is_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymethod',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='deliverymethod',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
