# Generated by Django 5.1.6 on 2025-04-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_order_promo_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_data',
            field=models.CharField(default='+7123456789', max_length=30, verbose_name='Контактные данные'),
        ),
    ]
