# Generated by Django 5.1.6 on 2025-04-16 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_order_phone_order_contact_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='max_discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Максимальная скидка'),
        ),
    ]
