# Generated by Django 5.1.6 on 2025-04-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_promocode_max_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_preorder',
            field=models.BooleanField(default=False, verbose_name='Под заказ'),
        ),
    ]
