# Generated by Django 5.1.6 on 2025-03-02 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('text', models.TextField(verbose_name='Текст статьи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Статус статьи')),
                ('published_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации статьи')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='articles/images/%Y/%m/%d')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article')),
            ],
            options={
                'verbose_name': 'Изображение для статьи',
                'verbose_name_plural': 'Изображения для статьи',
            },
        ),
    ]
