# Generated by Django 5.1.6 on 2025-03-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации статьи'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='articles.article', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='file',
            field=models.ImageField(upload_to='articles/images/%Y/%m/%d', verbose_name='Изображение'),
        ),
    ]
