# Generated by Django 5.1.6 on 2025-03-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='articles/previews/%Y/%m/%d', verbose_name='Превью'),
        ),
    ]
