import type { Metadata } from 'next';
import { Comfortaa } from 'next/font/google';
import './globals.css';
import { FloatingButtons, Header } from '@/components/widgets';
import { Footer } from '@/components/widgets/footer/Footer';

const comfortaa = Comfortaa({
  variable: '--font-comfortaa',
  subsets: ['cyrillic', 'latin'],
});

export const metadata: Metadata = {
  title: 'PlenkaPlace',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${comfortaa.variable} antialiased`}>
        <Header />
        <FloatingButtons />
        {children}
        <Footer />
      </body>
    </html>
  );
}
