// import { Product } from '@/components/entity';

// export const cameras: Product[] = [
//   {
//     id: '1',
//     title: 'Винтажный фотоаппарат Canon AE-1',
//     description: 'Классический плёночный фотоаппарат с ручным управлением.',
//     price: '15000',
//     images: [{ id: 1, image: '/mockup/AE1.jpg', product: 1 }],
//     product_type: { id: 1, title: 'Камеры' },
//     is_available_for_purchasing: true,
//     quantity: 120,
//     total: '20000',
//   },
//   {
//     id: '2',
//     title: 'Фотоаппарат Nikon FM2',
//     description: 'Механический плёночный фотоаппарат с высокой надёжностью.',
//     price: '18000',
//     images: [{ id: 2, image: '/mockup/FM2.jpg', product: 2 }],
//     product_type: { id: 1, title: 'Камеры' },
//     is_available_for_purchasing: true,
//     quantity: 95,
//     total: '22000',
//   },
//   {
//     id: '3',
//     title: 'Фотоаппарат Olympus OM-1',
//     description:
//       'Компактный и лёгкий плёночный фотоаппарат с отличной оптикой.',
//     price: '14000',
//     images: [{ id: 3, image: '/mockup/OM1.jpg', product: 3 }],
//     product_type: { id: 1, title: 'Камеры' },
//     is_available_for_purchasing: true,
//     quantity: 80,
//     total: '19000',
//   },
//   {
//     id: '4',
//     title: 'Фотоаппарат Pentax K1000',
//     description: 'Простой и надёжный фотоаппарат для начинающих.',
//     price: '12000',
//     images: [{ id: 4, image: '/mockup/K1000.jpg', product: 4 }],
//     product_type: { id: 1, title: 'Камеры' },
//     is_available_for_purchasing: true,
//     quantity: 70,
//     total: '17000',
//   },
//   {
//     id: '5',
//     title: 'Фотоаппарат Minolta X-700',
//     description:
//       'Популярный плёночный фотоаппарат с режимом приоритета диафрагмы.',
//     price: '16000',
//     images: [{ id: 5, image: '/mockup/X700.jpg', product: 5 }],
//     product_type: { id: 1, title: 'Камеры' },
//     is_available_for_purchasing: true,
//     quantity: 110,
//     total: '21000',
//   },
// ];

// export const films: Product[] = [
//   {
//     id: '6',
//     title: 'Плёнка Kodak Portra 400',
//     description: 'Цветная негативная плёнка для портретной и пейзажной съёмки.',
//     price: '1200',
//     images: [{ id: 6, image: '/mockup/kodak-portra-400.jpg', product: 6 }],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 200,
//     total: '1500',
//   },
//   {
//     id: '7',
//     title: 'Плёнка Fujifilm Superia X-TRA 400',
//     description: 'Универсальная цветная негативная плёнка для любых условий.',
//     price: '1100',
//     images: [{ id: 7, image: '/mockup/fujifilm-superia-400.jpg', product: 7 }],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 180,
//     total: '1400',
//   },
//   {
//     id: '8',
//     title: 'Плёнка Ilford HP5 Plus 400',
//     description: 'Чёрно-белая плёнка с высокой светочувствительностью.',
//     price: '1000',
//     images: [{ id: 8, image: '/mockup/ilford-hp5-plus-400.jpg', product: 8 }],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 150,
//     total: '1300',
//   },
//   {
//     id: '11',
//     title: 'Плёнка Kodak Ektar 100',
//     description: 'Цветная негативная плёнка с высокой насыщенностью цветов.',
//     price: '1300',
//     images: [{ id: 11, image: '/mockup/kodak-ektar-100.jpg', product: 11 }],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 170,
//     total: '1600',
//   },
//   {
//     id: '12',
//     title: 'Плёнка Cinestill 800T',
//     description:
//       'Цветная негативная плёнка для съёмки при искусственном освещении.',
//     price: '1500',
//     images: [{ id: 12, image: '/mockup/cinestill-800t.jpg', product: 12 }],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 140,
//     total: '1800',
//   },
//   {
//     id: '14',
//     title: 'Плёнка Lomography Color Negative 400',
//     description:
//       'Яркая и насыщенная цветная плёнка для творческих экспериментов.',
//     price: '900',
//     images: [
//       { id: 14, image: '/mockup/lomography-color-400.jpg', product: 14 },
//     ],
//     product_type: { id: 2, title: 'Плёнки' },
//     is_available_for_purchasing: true,
//     quantity: 95,
//     total: '1200',
//   },
// ];

// export const sets: Product[] = [
//   {
//     id: '9',
//     title: 'Набор для проявки плёнки',
//     description: 'Полный набор для самостоятельной проявки чёрно-белой плёнки.',
//     price: '5000',
//     images: [{ id: 9, image: '/mockup/development-kit.jpg', product: 9 }],
//     product_type: { id: 3, title: 'Наборы' },
//     is_available_for_purchasing: true,
//     quantity: 90,
//     total: '6000',
//   },
//   {
//     id: '10',
//     title: 'Набор для чистки фотоаппарата',
//     description: 'Набор инструментов для ухода за плёночными фотоаппаратами.',
//     price: '2500',
//     images: [{ id: 10, image: '/mockup/cleaning-kit.jpg', product: 10 }],
//     product_type: { id: 3, title: 'Наборы' },
//     is_available_for_purchasing: true,
//     quantity: 85,
//     total: '3000',
//   },
//   {
//     id: '13',
//     title: 'Набор для хранения плёнок',
//     description: 'Набор контейнеров для безопасного хранения плёнок.',
//     price: '2000',
//     images: [{ id: 13, image: '/mockup/film-storage-kit.jpg', product: 13 }],
//     product_type: { id: 3, title: 'Наборы' },
//     is_available_for_purchasing: true,
//     quantity: 75,
//     total: '2500',
//   },
//   {
//     id: '15',
//     title: 'Набор для сканирования плёнок',
//     description: 'Комплект для оцифровки плёнок в домашних условиях.',
//     price: '7000',
//     images: [{ id: 15, image: '/mockup/film-scanning-kit.jpg', product: 15 }],
//     product_type: { id: 3, title: 'Наборы' },
//     is_available_for_purchasing: true,
//     quantity: 110,
//     total: '8000',
//   },
// ];
